### ISSUE TITLE
Change password wrong username error is cryptic

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ar#101]
The error a user gets when they try to change their password but don't enter a valid username is cryptic: `Error retrieving account`

Arguably for security this is correct. However, that is also all we see in the error logs. It would be nice to add "username asdf not found to change password" or some such.

 _Imported from trac ticket [#101](http://trac.gpolab.bbn.com/idp-tools/ticket/101),  created by ahelsing on 05-18-2015 at 12:06, last modified: 05-18-2015 at 12:06_

**Comment by tcmitchell** [comment]
This is OBE with PR #115
