### ISSUE TITLE
Order entries in tables

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-ar#128]
Entries can move around in the tables. Order them in some way. For instance, order requests by date, most recent first. Similarly, order action logs by date, most recent first.

**Comment by charliemeyer** [comment]
What do you want the default ordering to be? This is a super easy param to set for datatables

**Comment by charliemeyer** [comment]
Also, clicking the header of any column in any of the tables will sort that table by that attribute, by default with how datatables is working already

**Comment by tcmitchell** [comment]
As in the ticket description, probably the request date, most recent first for account request tables. For action logs, probably the action time, most recent first.
