### ISSUE TITLE
'NO_PHONE_NUMBER' causes error on approval

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-ar#146]
An account request included 'NO_PHONE_NUMBER' in the phone number field. This caused an error upon approval:

```
PHP Warning:  ldap_add(): Add: Invalid syntax in /usr/share/geni-ar/protected/approve.php on line 63
```

Do a better job verifying the phone number field.

**Comment by ahelsing** [comment]
Here's a Regex to validate phone numbers in PHP: https://stackoverflow.com/a/20971688

Finding what is legal in LDAP is a pain.
See
https://www.ietf.org/rfc/rfc4517.txt
https://www.itu.int/rec/T-REC-E.123-198811-S/en

I think these are legal characters, and at least 1 non whitespace character is required:

`+ ()0-9a-zA-Z#*/.-~,`

**Comment by ahelsing** [comment]
Testing with our LDAP server shows it fails on `*`, `_`, `#`, `~`. All other characters from above are accepted.

**Comment by ahelsing** [comment]
Note that the HTML5 `tel` input type is only honored by Safari. For other browsers, client side validation of the phone number would require extra javascript. Skipping that for now.

**Comment by ahelsing** [comment]
For now, err on the side of allowing lots of variation in phone numbers, including things that are clearly bogus but at least use only legal characters. Handling full international phone variations would require using EG https://github.com/googlei18n/libphonenumber

**Comment by ahelsing** [comment]
Using this regex: `/^[\+\(\)0-9a-zA-Z\/\.\-\,]+[\+ \(\)0-9a-zA-Z\/\.\-\,]*$/`
