### ISSUE TITLE
Matching on email finds wrong request

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-ar#147]
There are a few places where the database query matches on email address as if it is a unique key, but it is not. Denied requests can have the same email address as live requests. Stop matching on email address. Use the request id instead.

For instance, when a new request is received that includes an email address that matches a denied request, the email announcing that request can contain the new information or the information from the previously denied account request.

This is also the case with approving account requests via approve.php. It matches the email address but should match the request id (which it has) instead.

**Comment by ahelsing** [comment]
The only place that seems to have this problem is confirmemail. We only have the email address, and we know the expected request state. But currently the code looks up the request multiple times. Instead, look it up once and then use the id of the request that has been confirmed.

**Comment by ahelsing** [comment]
also adding comments about other tables where we look up by email address (for password reset, action logs), to note that action logs has a potential issue but not a serious one; none worth acting on.

**Comment by ahelsing** [comment]
Fixed with pull request #157.
