### ISSUE TITLE
/usr/share/geni-ar/etc/settings.php suggests an LDAP port of 111

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ar#26]
The default setting in `/usr/share/geni-ar/etc/settings.php` has:

```
$ldap_port = 111;
```

which is the port for SUNRPC, not for LDAP (LDAP is 389).

 _Imported from trac ticket [#26](http://trac.gpolab.bbn.com/idp-tools/ticket/26),  created by chaos on 09-11-2013 at 16:51, last modified: 09-13-2013 at 16:08_

**Comment by ahelsing** [comment]
Like the priority says, this is trivial.

_Trac comment by chaos on 09-11-2013 at 16:52_

**Comment by ahelsing** [comment]
I did that on purpose.  I thought we weren't supposed to use any real values in the example file.  Easy to change if you want the real value.  I picked 111 randomly. 

_Trac comment by phelinek on 09-11-2013 at 17:34_

**Comment by tcmitchell** [comment]
We shouldn't use any real database names, usernames, hostnames, email addresses, etc.

The LDAP port is fine to leave as 389. My fault for the communication failure.

_Trac comment by tmitchel (github user: tcmitchell) on 09-11-2013 at 17:36_
