### ISSUE TITLE
schema initialization script fails

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ar#27]
Using version 0.2:
- Create a database and user:

```
aslund,[~],17:07(0)$ sudo -u postgres /usr/bin/createuser -S -D -R accreq

aslund,[~],17:07(0)$ sudo -u postgres /usr/bin/psql -c "\\password accreq"
Enter new password: 
Enter it again: 

aslund,[~],17:07(0)$ /usr/bin/sudo -u postgres /usr/bin/createdb accreq

aslund,[~],17:07(0)$
```
- Run the insertion script:

```
aslund,[~],17:07(0)$ psql -U accreq -h localhost accreq -f /usr/share/geni-ar/db/postgresql/schema.sql
SET
SET
DROP TABLE
psql:/usr/share/geni-ar/db/postgresql/schema.sql:30: ERROR:  syntax error at or near "at"
LINE 13:   request_ts timestamp DEFAULT NOW() at time zone 'utc',
                                              ^
aslund,[~],17:08(3)$ 
```

 _Imported from trac ticket [#27](http://trac.gpolab.bbn.com/idp-tools/ticket/27),  created by chaos on 09-11-2013 at 17:09, last modified: 09-13-2013 at 16:07_

**Comment by tcmitchell** [comment]
See http://stackoverflow.com/questions/16609724/using-current-time-in-utc-as-default-value-in-postgresql

I think what's there needs parentheses. Obviously it also needs to be tested.

_Trac comment by tmitchel (github user: tcmitchell) on 09-11-2013 at 17:24_

**Comment by ahelsing** [comment]
I added the change to utc timestamps after the table was created.  The default works when I insert new entries into the db.  I didn't create the new table with the commands you're using (I'm new to database creation, sorry!).  I logged into the database and manually created the new table, then manually changed the column to default to utc. But I will make some dummy schemas (with utc timestamps) and test database creation using the above commands to debug this.

_Trac comment by phelinek on 09-11-2013 at 17:49_

**Comment by ahelsing** [comment]
Adding the parenthesis fixed the problem.

_Trac comment by phelinek on 09-12-2013 at 10:50_

**Comment by ahelsing** [comment]
Looks good for me now too:

```
aslund,[~],13:32(0)$ psql -U accreq -h localhost accreq -f /usr/share/geni-ar/db/postgresql/schema.sql
SET
SET
DROP TABLE
CREATE TABLE
DROP TABLE
CREATE TABLE
aslund,[~],13:32(0)$ 
```

_Trac comment by chaos on 09-13-2013 at 13:32_
