### ISSUE TITLE
geni-ar package should include python-psycopg2 as a dependency

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ar#28]
The `geni-add-log` and `geni-convert-logs` commands now require the `python-psycopg2` package on ubuntu, but package install doesn't include this.

 _Imported from trac ticket [#28](http://trac.gpolab.bbn.com/idp-tools/ticket/28),  created by chaos on 09-13-2013 at 13:17, last modified: 09-13-2013 at 16:06_

**Comment by ahelsing** [comment]
Pam warned me about this, and i can install the package by hand to test, but i figured why not have a ticket.

_Trac comment by chaos on 09-13-2013 at 13:18_

**Comment by tcmitchell** [comment]
Added python-psycopg2 to browser:geni-ar/debian/control as dependency.

_Trac comment by tmitchel (github user: tcmitchell) on 09-13-2013 at 14:32_
