### ISSUE TITLE
README.Debian should instruct the installer to create the accreq database and pgsql user

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ar#47]
Before you can do step 1 of `/usr/share/doc/geni-ar/README.Debian`, you need to install the accreq database and user.  We've been doing this in GPO lab using a procedure along the lines of:

```
# Create the user
sudo -u postgres /usr/bin/createuser -S -D -R accreq

# Set the password
sudo -u postgres /usr/bin/psql -c "\\password accreq"
Enter new password: 
Enter it again: 

# Create the database
/usr/bin/sudo -u postgres /usr/bin/createdb accreq
```

The documentation should say that this is necessary.

 _Imported from trac ticket [#47](http://trac.gpolab.bbn.com/idp-tools/ticket/47),  created by chaos on 10-01-2013 at 13:47, last modified: 10-03-2013 at 16:37_

**Comment by ahelsing** [comment]
My sense of consistency compelled me to create this ticket.  I don't care even slightly whether/when it gets closed.

_Trac comment by chaos on 10-01-2013 at 13:48_

**Comment by tcmitchell** [comment]
Updated README.Debian accordingly.

_Trac comment by tmitchel (github user: tcmitchell) on 10-03-2013 at 16:37_
