### ISSUE TITLE
Add URL to account request email

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-ar#57]
It would be convenient if the account request email included the URL for managing requests. That way it would be a quick click in a mail reader to go to the page to handle the request.

The email currently includes the line:
  See table idp_account_request for complete details.
That's probably no longer relevant, and a holdover from the previous system for handling the requests. that line should go away.

 _Imported from trac ticket [#57](http://trac.gpolab.bbn.com/idp-tools/ticket/57),  created by tmitchel on 10-14-2013 at 10:17, last modified: 01-03-2014 at 10:25_

**Comment by ahelsing** [comment]
Duplicate of ticket #55?

_Trac comment by ahelsing on 10-16-2013 at 13:21_
