### ISSUE TITLE
accent on a character causes LDAP error

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ar#64]
symptom: `ERROR: Failed to create new ldap account`

```
[Sun Oct 27 13:57:26 2013] [error] [client 128.89.255.249] PHP Warning:  ldap_add( Add: Invalid syntax in /usr/share/geni-ar/protected/request_actions.php on line 149, referer: https://shib-idp.geni.net/manage/display_requests.php
```

line 149 is:`$ret = ldap_add($ldapconn, $new_dn, $attrs);`

The field with the accent was institution:
`UPMC, Université Pierre et Marie Currie, Paris`

 _Imported from trac ticket [#64](http://trac.gpolab.bbn.com/idp-tools/ticket/64),  created by ahelsing on 10-27-2013 at 14:08, last modified: 06-18-2014 at 16:24_

**Comment by ahelsing** [comment]
See ticket #30

_Trac comment by ahelsing on 11-05-2013 at 14:50_

**Comment by ahelsing** [comment]
We had another example of this with first name.

Fields from users need to be utf8_encoded before insertion into LDAP.

_Trac comment by ahelsing on 02-17-2014 at 09:24_

**Comment by tcmitchell** [comment]
`utf8_encode` works for putting non-ascii characters into LDAP. This change needs to be tested with Shibboleth before incorporating it to be sure non-ascii characters can be transported and consumed properly by downstream systems.

_Trac comment by tmitchel (github user: tcmitchell) on 02-28-2014 at 17:14_

**Comment by tcmitchell** [comment]
This is tied up in a broader effort to support Unicode/UTF8 in the portal and clearinghouse. Putting it on hold for now.

When we do pick it up, we think the right way to handle this is:
- Internally, always handle strings as Unicode. This means while processing requests in the PHP code. Convert from UTF8 to Unicode when data is received from LDAP, PostgreSQL, and web form submits.
- Encode in UTF8 whenever values are sent to external systems (namely LDAP, PostgreSQL, and web pages

_Trac comment by tmitchel (github user: tcmitchell) on 06-18-2014 at 16:24_
