### ISSUE TITLE
instead of copying e-mail templates to /etc/geni-ar/, have the code fall back to the packaged versions

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ar#79]
The geni-ar package postinst script copies e-mail template files into /etc/geni-ar/, but only if those files don't exist.

When upgrading, this means that no templates get updated, because the postinst can't differentiate between unmodified copies of the files from a previous version, and copies that the local admins have intentionally modified.

There are probably a few ways to clean this up, but a simple one might be for the code which is trying to use templates to check and see if a version exists in /etc/geni-ar/, and, if one doesn't, to fall back to the same filename in /usr/share/geni-ar/etc/.  So that's my provisional suggestion.

 _Imported from trac ticket [#79](http://trac.gpolab.bbn.com/idp-tools/ticket/79),  created by chaos on 01-24-2014 at 17:33, last modified: 02-27-2014 at 16:14_

**Comment by ahelsing** [comment]
We don't actually need this fixed for GPO lab --- since we config-manage all configs we modify, i'm comfortable simply prepending:

```
sudo rm /etc/geni-ch/*-email.txt
```

to our update procedure, which lets the update have a clean slate.

But the package behavior seems wrong, so i wanted to make a ticket about it.

_Trac comment by chaos on 01-24-2014 at 17:34_

**Comment by ahelsing** [comment]
The implemented fix has a typo (see [https://github.com/GENI-NSF/geni-ar/issues/82\]).

However, that notwithstanding, the implemented fix did not actually resolve the problem i was reporting here: the desired behavior is:
1. Allow sites to override templates by changing files in /etc/geni-ar/
2. Allow new versions of the package to upgrade the default templates which get used if the site does not override them

My suggestion here was that the code include the ability to fall back to the packaged version of the template _instead of'' having the package postinstall copy the files into /etc/geni-ar/.

The current implementation has the ability to fall back to the packaged version of each template, but ''also_ copies the files into /etc/geni-ar/.  So this still doesn't meet item 2 of the desired behavior.

_Trac comment by chaos on 02-05-2014 at 11:56_

**Comment by ahelsing** [comment]
This continues not to be a blocker: it just means a workaround for infra to delete all the old config files each time we upgrade.

_Trac comment by chaos on 02-05-2014 at 11:57_

**Comment by tcmitchell** [comment]
I need to update the package scripts to stop doing the copy to `/etc/geni-ar`. I'll try to do that for the next release.

_Trac comment by tmitchel (github user: tcmitchell) on 02-05-2014 at 12:22_

**Comment by tcmitchell** [comment]
The `postinst` script has been removed.

_Trac comment by tmitchel (github user: tcmitchell) on 02-27-2014 at 16:14_
