### ISSUE TITLE
reply-to of portal-help is hardcoded in at least one case

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ar#80]
The "thanks for requesting an account e-mail" i sent myself on shib-idp1 had:

```
Date: Mon, 27 Jan 2014 12:15:24 -0500 (EST)
From: www-data <www-data@gpolab.bbn.com>
To: chaos7@gpolab.bbn.com
Subject: GENI Identity Provider Account Request Received
Reply-to: portal-help@geni.net
```

All of the e-mail settings for shib-idp1 use gpo-ops, not portal-help, so i think this reply-to indicates a hard-coded recipient, and it looks like there are a few:

```
$ dpkg -L geni-ar | xargs grep -l portal-help@geni.net
/usr/share/geni-ar/protected/request_actions.php
/usr/share/geni-ar/protected/acct_actions.php
/usr/share/geni-ar/protected/tutorial_actions.php
/usr/share/geni-ar/www/handlerequest.php
/usr/share/geni-ar/www/request.html
```

Instead, the `$idp_approval_email` variable should be used.

Also, while you're in there, this is truly trivial, but the capitalization of "Reply-To:" (capital T) is more standard IMO, and is used other places in the code.

 _Imported from trac ticket [#80](http://trac.gpolab.bbn.com/idp-tools/ticket/80),  created by chaos on 01-27-2014 at 12:22, last modified: 02-05-2014 at 12:56_

**Comment by tcmitchell** [comment]
The instance of `portal-help@geni.net` in browser:geni-ar/www/request.html should probably be returned to `help@geni.net`. It's a help link, not a header for a generated email. Not sure why it got caught up in the email header commit.

Otherwise, these can all be fixed, pretty easily. Consider introducing a function that generates the standard header fields so we don't have to adjust headers in multiple places throughout the code.

_Trac comment by tmitchel (github user: tcmitchell) on 01-27-2014 at 14:27_

**Comment by ahelsing** [comment]
Added a new config variable in settings.php: idp_help_email.  This will require a puppet change.

Added $AR_EMAIL_HEADERS to ar_constants.php to standardize email headers.  This has precendence, auto-submitted, and reply-to headers.

Changed back the email address for help on the request form to "help@geni.net".  I thought that portal-help was the correct address, sorry.

_Trac comment by phelinek on 01-29-2014 at 15:47_

**Comment by ahelsing** [comment]
Removed idp_help_email config variable because idp_approval_email is already set to portal-help.  Use idp_approval_email as Reply-to 

_Trac comment by phelinek on 01-29-2014 at 16:25_

**Comment by ahelsing** [comment]
Also changed Reply-to to Reply-To

_Trac comment by phelinek on 01-29-2014 at 17:00_

**Comment by ahelsing** [comment]
Verified that where reply-to works (see [https://github.com/GENI-NSF/geni-ar/issues/81\]), it is no longer set to portal-help on my test system, and that portal-help no longer appears to be hardcoded anywhere in the codebase.

_Trac comment by chaos on 02-05-2014 at 12:56_
