### ISSUE TITLE
typo in path to notification e-mail

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ar#82]
When i approve a new account, i see this in the apache error log:

 [Wed Feb 05 11:43:31 2014] [error] [client 128.89.254.73] PHP Warning:  fopen(/etc/geni-arnotification-email.txt): failed to open stream: No such file or directory in /usr/share/geni-ar/protected/request_actions.php on line 188, referer: https://shib-idp1.gpolab.bbn.com/manage/display_requests.php

 _Imported from trac ticket [#82](http://trac.gpolab.bbn.com/idp-tools/ticket/82),  created by chaos on 02-05-2014 at 11:45, last modified: 02-27-2014 at 16:02_

**Comment by ahelsing** [comment]
Notification e-mails _are'' successfully sent.

It looks to me like the ar_constants.php is inconsistent about having a slash at the end of the paths:

```
$AR_TEMPLATE_PATH = "/etc/geni-ar";
$AR_ALT_TEMPLATE_PATH = "/usr/share/geni-ar/etc/";
```

Does this mean that lookups in $AR_TEMPLATE_PATH will always fail and fall back to $AR_ALT_TEMPLATE_PATH?  If so, that means that there's no problem as long as we're not trying to override templates, but we can't override templates.

Right now, we're not trying to override any templates, so this isn't a blocker ''based on my current understanding of the behavior_.

_Trac comment by chaos on 02-05-2014 at 11:48_

**Comment by tcmitchell** [comment]
I saw the same error with `tutorial-email.txt`:
 PHP Warning:  fopen(/etc/geni-artutorial-email.txt): failed to open stream: No such file or directory in /usr/share/geni-ar/protected/tutorial_actions.php on line 190

_Trac comment by tmitchel (github user: tcmitchell) on 02-27-2014 at 11:36_

**Comment by tcmitchell** [comment]
email template support has been revamped. PATH variables are now always directory names (and have been changed to say DIRECTORY). Files are constructed by appending a '/' and a file name.

All template loading is now in a utility method so it can be managed and updated more readily.

_Trac comment by tmitchel (github user: tcmitchell) on 02-27-2014 at 16:02_
