### ISSUE TITLE
Allow confirming the request on password change requests

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ar#83]
We should allow Confirm Requester on password change requests. We want to confirm that the request came from the person whose email this is.

 _Imported from trac ticket [#83](http://trac.gpolab.bbn.com/idp-tools/ticket/83),  created by ahelsing on 02-10-2014 at 08:26, last modified: 04-02-2014 at 15:22_

**Comment by tcmitchell** [comment]
This is OBE with PR #115
