### ISSUE TITLE
Allow Add Note and Email Requester and Deny on Password Change request

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ar#84]
Allow doing things like adding a note and emailing the requester on a password change request. I wanted to note that I had emailed the experimenter to confirm that they tried to change their password, and couldn't do that either.

 _Imported from trac ticket [#84](http://trac.gpolab.bbn.com/idp-tools/ticket/84),  created by ahelsing on 02-10-2014 at 08:35, last modified: 04-02-2014 at 15:22_

**Comment by tcmitchell** [comment]
This is OBE with PR #115
