### ISSUE TITLE
Add Note on request waiting on requester got blank screen

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ar#85]
I did Add Note on an account request waiting on the experimenter, and got back a blank screen. I suspect a server error.

 _Imported from trac ticket [#85](http://trac.gpolab.bbn.com/idp-tools/ticket/85),  created by ahelsing on 02-10-2014 at 08:39, last modified: 02-10-2014 at 08:40_

**Comment by ahelsing** [comment]
Note that the note itself was added

_Trac comment by ahelsing on 02-10-2014 at 08:40_

**Comment by tcmitchell** [comment]
The next location in `add_note.php` is determined by the `request_state`. In the case of waiting on requester the state is "CONFIRM_REQUESTER". There is no clause for that state in the block determining the next location in `add_note.php`.

At a minimum there should be a default location, so add an `else` clause that goes to `display_requests.php`. If a specific location is desired for this state, add a clause for the "CONFIRM_REQUESTER" state as well.

**Comment by tcmitchell** [comment]
I added a case specific to CONFIRM_REQUESTER and also added a default case.
