### ISSUE TITLE
display_requests.php lists the wrong performer for tutorial account creations

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ar#89]
The "Approved Account Requests" section of e.g. [https://shib-idp.geni.net/manage/display_requests.php] displays the wrong person's name under "Performer" when tutorial accounts are created.  The action log at [https://shib-idp.geni.net/manage/action_log.php] is correct.

 _Imported from trac ticket [#89](http://trac.gpolab.bbn.com/idp-tools/ticket/89),  created by chaos on 02-18-2014 at 14:50, last modified: 02-26-2014 at 18:30_

**Comment by ahelsing** [comment]
I believe i found the bug --- in display_requests.php, the query used to get the performer is:

```
  $sql = "SELECT performer, action_ts from idp_account_actions WHERE uid='" . $uname . "' and action_performed='Account Created' ORDER BY id desc";
```

but for a tutorial account, the action is "Created Tutorial Account" not "Account Created".  So it probably just keeps the previous performer value.

It's probably worth checking when this is fixed for other places in display_requests.php where the same thing happens.

_Trac comment by chaos on 02-18-2014 at 14:52_

**Comment by tcmitchell** [comment]
Add an OR clause to catch both actions. Also extracted the action strings into constants. And set performer and action timestamp to an empty cell if none is found via the query.

_Trac comment by tmitchel (github user: tcmitchell) on 02-26-2014 at 18:30_
