### ISSUE TITLE
Cannot deny a password change request

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ar#91]
We got a password change request for someone who does not have an account.

But the system will not let me deny the request. 

 _Imported from trac ticket [#91](http://trac.gpolab.bbn.com/idp-tools/ticket/91),  created by ahelsing on 02-27-2014 at 09:38, last modified: 06-18-2014 at 14:54_

**Comment by tcmitchell** [comment]
The user does have an account. It is not possible to create a password change request without matching a valid account.

The fact remains, however, that a password change request can only be approved, not denied. It's easy to imagine cases where denying a password change request might be useful, so this feature is still desirable.

_Trac comment by tmitchel (github user: tcmitchell) on 02-27-2014 at 16:32_
