### ISSUE TITLE
notes with punctuation fail

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ar#94]
Add Note: if the text has punctuation in it, it appears to fail. I don't know which punctuation is problematic, but a note with a colon, comma, period, and apostrophe failed.

 _Imported from trac ticket [#94](http://trac.gpolab.bbn.com/idp-tools/ticket/94),  created by ahelsing on 05-22-2014 at 13:58, last modified: 05-22-2014 at 14:00_

**Comment by tcmitchell** [comment]
A note with a period worked for me.

**Comment by charliemeyer** [comment]
Just tested this, I think it's the apostrophe that did it. Will check this out
