### ISSUE TITLE
Increase size of Reason

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ar#98]
On the account request page, increase the size of the 'Reason' field. It is currently '50'. Perhaps make this a text area that is 3 lines by 50-80 chars?

 _Imported from trac ticket [#98](http://trac.gpolab.bbn.com/idp-tools/ticket/98),  created by ahelsing on 01-12-2015 at 15:59, last modified: 01-12-2015 at 15:59_

**Comment by ahelsing** [comment]
Field may be called 'purpose'.  Add text encouraging people to provide enough input so that we can make an intelligent decision.

**Comment by tcmitchell** [comment]
Complete. 3 lines by 50 columns. Alignment is a bit off, maybe a CSS wizard can fix that.
