### ISSUE TITLE
Remove Henry from email to leads

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ar#99]
remove hyeh@bbn.com from the email addresses when we email leads

 _Imported from trac ticket [#99](http://trac.gpolab.bbn.com/idp-tools/ticket/99),  created by ahelsing on 03-13-2015 at 13:08, last modified: 03-19-2015 at 09:52_

**Comment by tcmitchell** [comment]
This value is configured by puppet in the file `/etc/geni-ar/settings.php`. A request to update the puppet configuration has been opened as http://groups.geni.net/syseng/ticket/6475

_Trac comment by tmitchel (github user: tcmitchell) on 03-16-2015 at 09:14_

**Comment by ahelsing** [comment]
and now done

_Trac comment by ahelsing on 03-19-2015 at 09:52_
